spring:
    config:
        import:
            - "classpath:config.yml"
    datasource:
        url: ${url}
#       username 사용 시 host name이 전달됨... name으로 명시
        username: ${name}
        password: ${password}
        driver-class-name: com.mysql.cj.jdbc.Driver
    aws:
        access-key-cognito: ${aws.access-key-cognito}
        secret-key-cognito: ${aws.secret-key-cognito}
        cognito:
            userPoolId: ${aws.cognito.userPoolId}
            region: ${aws.cognito.region}
    resource:
        origin: ${origin}

    servlet:
        multipart:
            maxFileSize: 10MB # 파일 하나의 최대 크기
            maxRequestSize: 30MB  # 한 번에 최대 업로드 가능 용량

    jpa:
        hibernate:
            ddl-auto: update
        show-sql: true
        properties:
            hibernate:
                show_sql: true
                format_sql: true
                dialect: org.hibernate.dialect.MySQLDialect